### ISSUE TITLE
Formatters are not called correctly

### ISSUE THREAD

**Issue by kksandr7** [adorade/gulp-stylelint-esm#20]
Hello. At the moment I am not getting any error report in the output.

The problem is that the second argument `returnValue` is required for the [Formatter](https://github.com/stylelint/stylelint/blob/2be707216a2a3d1061fb4048fc8e550d085f405d/types/stylelint/index.d.ts#L184) call and the call fails when trying to get [ruleMetadata](https://github.com/stylelint/stylelint/blob/2be707216a2a3d1061fb4048fc8e550d085f405d/lib/formatters/stringFormatter.mjs#L254).

I suggest passing the entire [LinterResult](https://github.com/stylelint/stylelint/blob/2be707216a2a3d1061fb4048fc8e550d085f405d/types/stylelint/index.d.ts#L548) object to the reporter instead of the [LinterResult.results](https://github.com/stylelint/stylelint/blob/2be707216a2a3d1061fb4048fc8e550d085f405d/types/stylelint/index.d.ts#L554) grouping. This will solve the problem of passing the results to the formatter.

**Comment by adorade** [comment]
Hi @kksandr7 thank you for reporting this issue.
Unfortunately, PR #21 didn't pass the test after I approved the review.
Can you tell me which version of `stylelint` and `gulp` you use? I want to reproduce what you do so I can figure out what's going on.

**Comment by adorade** [comment]
I will check when I will have free time available. Keep in touch!

**Comment by adorade** [comment]
I have tested the changes made. Regrettably, they are not functioning with **gulp v5**. I will conduct further investigations, as there may be a compatibility issue with **gulp v5**. It is essential for the plugin to be compatible with both **gulp versions 4 and 5**.
Without any modifications, the plugin is compatible with **gulp v4** and any version of **stylelint greater than 16**.

**Comment by adorade** [comment]
I have tested the changes made. Regrettably, they are not functioning with `gulp v5`. I will conduct further investigations, as there may be a compatibility issue with `gulp v5`. It is essential for the plugin to be compatible with both `gulp versions 4 and 5`.
Without any modifications, the plugin is compatible with **_gulp v4_** and any version of **_stylelint greater than 16_**.

**Comment by adorade** [comment]
Test passed with `gulp v4`, but not `gulp v5`.

`Plugin Functionality › should emit an error on streamed file`
